Use libiberty functionality.
Defining HAVE_DECL_BASENAME to 1 is required to include libiberty.h
Without this, a compiler error message is issued.

wrapper.cpp:5:
include/libiberty.h:112:14: error: conflicting declaration of
C function 'char* __xpg_basename(const char*)'
  112 | extern char *basename (const char *) ATTRIBUTE_RETURNS_NONNULL ATTRIBUTE_NONNULL(1);
      |              ^~~~~~~~
/usr/include/libgen.h:34:14: note: previous declaration 'char* __xpg_basename(char*)'
   34 | extern char *__xpg_basename (char *__path) __THROW;

This macro definition is from <dir_tobuild_gcc>/gcc/auto-host.h
(gcc/config.h include auto-host.h)